"""
ComfyUI Custom Node - Save Image (Advanced)
Advanced terminal save node, built around the LayerStyle "SaveImage Plus
(Advanced)" behaviour the user already runs in every workflow, extended with
TIFF, WEBP and multi-resolution ICO output.

Features
--------
- Formats: png, jpg, webp, webp (lossless), tiff (LZW, lossless), ico
- %date / %time tokens in custom_path and filename_prefix
- Optional timestamp in the filename: none, second, millisecond
- Quality control (per format: png compression level, jpg/webp quality)
- Metadata: PNG text chunks / EXIF UserComment JSON - honouring the core
  --disable-metadata flag, same as the other save nodes in this ecosystem
- Invisible blind watermark (QR payload embedded in the RGB image,
  extractable with the blind_watermark library, password_img=1 password_wm=1)
- Optional preview image in the UI when saving to a custom_path
- Per-file "Saved image to <full path>" log lines

ICO note: unlike the broken multi-resolution approach of some other packs
(pre-resizing copies and letting PIL resample from the smallest one), the
entries here are always generated by PIL from the full-resolution source.
"""

import datetime
import json
import logging
import math
import os
import random

import numpy as np
import torch
from PIL import Image
from PIL.ExifTags import Base as ExifBase
from PIL.PngImagePlugin import PngInfo

import folder_paths

try:
    import args
except ImportError:  # core flag module - always present inside ComfyUI
    args = None

_P = "\033[38;5;141m[HWP Save Image]\033[38;5;41m "
_R = "\033[0m"


def _log(msg, level="info"):
    getattr(logging, level)(f"{_P}{msg}{_R}")


class HWPImageSave:
    CATEGORY = "HWP"
    RETURN_TYPES = ()
    FUNCTION = "save_images"
    OUTPUT_NODE = True

    FORMATS = ["png", "jpg", "webp", "webp (lossless)", "tiff", "ico"]
    EXTENSIONS = {
        "png": "png",
        "jpg": "jpg",
        "webp": "webp",
        "webp (lossless)": "webp",
        "tiff": "tiff",
        "ico": "ico",
    }
    # multi-resolution presets for ICO; entries are generated from the
    # full-resolution source image, so every size is a proper downscale
    ICO_PRESETS = {
        "Small (32, 48, 64)": (32, 48, 64),
        "Medium (64, 128, 256)": (64, 128, 256),
        "Large (128, 256, 512)": (128, 256, 512),
    }

    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "images": ("IMAGE",),
                "custom_path": ("STRING", {"default": ""}),
                "filename_prefix": ("STRING", {"default": "comfyui"}),
                "timestamp": (["None", "second", "millisecond"],),
                "format": (cls.FORMATS,),
                "quality": ("INT", {"default": 80, "min": 10, "max": 100, "step": 1}),
                "ico_sizes": (list(cls.ICO_PRESETS.keys()),),
                "meta_data": ("BOOLEAN", {"default": False}),
                "blind_watermark": ("STRING", {"default": ""}),
                "preview": ("BOOLEAN", {"default": True}),
            },
            "hidden": {
                "prompt": "PROMPT",
                "extra_pnginfo": "EXTRA_PNGINFO",
            },
        }

    # ------------------------------------------------------------------
    # helpers
    # ------------------------------------------------------------------
    @staticmethod
    def _random_name(prefix, suffix, length):
        alphabet = "abcdefghijklmnopqrstuvxyz0123456789"
        return prefix + "".join(random.choice(alphabet) for _ in range(length)) + suffix

    @staticmethod
    def _base_wm_size(width, height):
        # target watermark pixel size: ~1.25% of the image area, 90% margin
        # (same formula as LayerStyle). Only used to pick px-per-module below.
        return max(int(math.sqrt(width * height * 0.015625) * 0.9), 21)

    @staticmethod
    def _qr_module_count(text):
        """QR module count (incl. 1-module quiet zone each side) that *text*
        needs at EC-H. EC-H (30% recovery) is the most robust -- which is
        what a noisy DCT blind watermark needs -- at the cost of a larger
        code than EC-M/L would give for the same text."""
        import qrcode
        qr = qrcode.QRCode(version=1,
                           error_correction=qrcode.constants.ERROR_CORRECT_H,
                           border=1)
        qr.add_data(text.encode("utf-8"))
        qr.make(fit=True)
        return 21 + 4 * (qr.version - 1) + 2  # modules + 2*quiet-zone

    def _wm_params(self, width, height, text):
        """Size the watermark for *text* on a width x height host.

        Returns (wm_size, k, M): a crisp M x M module QR rendered at
        k px per module (wm_size = M * k), or None when the host is too
        small to carry the QR (blind_watermark holds one bit per 4x4 haar
        block, so its capacity in bits is (W//2//4) * (H//2//4) and the
        embedded bitmap must be strictly smaller than that)."""
        M = self._qr_module_count(text)
        k = max(1, self._base_wm_size(width, height) // M)
        wm_size = M * k
        cap = ((width + 1) // 2 // 4) * ((height + 1) // 2 // 4)
        if wm_size * wm_size >= cap:
            _log(f"blind watermark too large for {width}x{height}: QR needs "
                 f"{wm_size}x{wm_size}={wm_size * wm_size} bits, host holds "
                 f"{cap}; saving without it", "warning")
            return None
        return wm_size, k, M

    @staticmethod
    def _wm_bits(text, k, M):
        """Crisp QR bitstream (light=1 / dark=0), each module an exact
        k x k block -- built with np.kron, no resampling, so the finder
        patterns never alias the way a BICUBIC downscale would."""
        import qrcode
        qr = qrcode.QRCode(version=1,
                           error_correction=qrcode.constants.ERROR_CORRECT_H,
                           border=1)
        qr.add_data(text.encode("utf-8"))
        qr.make(fit=True)
        grid = np.pad(np.array(qr.modules, dtype=np.uint8), 1)  # M x M, 1=dark
        big = np.kron(grid, np.ones((k, k), dtype=np.uint8))    # (Mk) x (Mk)
        assert big.shape == (M * k, M * k)
        return (1 - big.astype(bool)).flatten()  # light=1, dark=0

    def _build_metadata(self, prompt, extra_pnginfo, fmt):
        """Return save kwargs carrying workflow metadata, or {} when the
        user disabled it / core runs with --disable-metadata / the format
        cannot store it (ico)."""
        if not meta_data_enabled():
            return {}
        if fmt == "ico":
            return {}
        if fmt == "png":
            metadata = PngInfo()
            if prompt is not None:
                metadata.add_text("prompt", json.dumps(prompt))
            if extra_pnginfo is not None:
                for x in extra_pnginfo:
                    metadata.add_text(x, json.dumps(extra_pnginfo[x]))
            return {"pnginfo": metadata}
        # jpg / webp / tiff: JSON blob in the EXIF UserComment tag,
        # same layout Apolonia's node uses
        metadata = {}
        if prompt is not None:
            metadata["prompt"] = prompt
        if extra_pnginfo is not None:
            metadata.update(extra_pnginfo)
        exif = Image.Exif()
        exif[ExifBase.UserComment] = json.dumps(metadata, ensure_ascii=False)
        return {"exif": exif}

    def _apply_blind_watermark(self, img, text):
        """Embed *text* invisibly (full-RGB QR payload, extractable with the
        blind_watermark library, password_img=1 password_wm=1). Returns the
        watermarked image in the original mode, or None when the libraries
        are missing, the image can't carry the QR, or embedding failed
        (image is then saved unwatermarked)."""
        try:
            import cv2
            from blind_watermark import WaterMark
        except ImportError as e:
            _log(f"blind watermark skipped, missing library: {e}", "warning")
            return None

        try:
            params = self._wm_params(img.width, img.height, text)
            if params is None:
                return None
            _, k, M = params
            # Embed in the full RGB image (not the U channel): PNG can only
            # store RGB/RGBA, so a YCbCr round-trip on save would shift the
            # U channel and corrupt the DCT watermark. The RGB->RGB save is
            # lossless, so the embedded bits survive to disk.
            rgb = img.convert("RGB")
            host_bgr = cv2.cvtColor(
                np.array(rgb, dtype=np.uint8), cv2.COLOR_RGB2BGR
            )
            wm_bits = self._wm_bits(text, k, M)
            bwm = WaterMark(password_img=1, password_wm=1)
            bwm.read_img(img=host_bgr)
            bwm.read_wm(wm_bits, mode="bit")
            embedded = bwm.embed(compression_ratio=100)  # float32 BGR array
            out = Image.fromarray(cv2.cvtColor(
                np.clip(embedded, 0, 255).astype(np.uint8),
                cv2.COLOR_BGR2RGB,
            ))
            if img.mode == "RGBA":
                r, g, b = out.split()
                out = Image.merge("RGBA", [r, g, b, img.split()[-1]])
            return out
        except Exception as e:
            _log(f"blind watermark failed ({e}), saving without it", "warning")
            return None

    @staticmethod
    def _flatten_alpha(img):
        """Composite an RGBA image over white (for formats without alpha)."""
        if img.mode != "RGBA":
            return img
        base = Image.new("RGB", img.size, (255, 255, 255))
        base.paste(img, mask=img.split()[-1])
        return base

    # ------------------------------------------------------------------
    # main
    # ------------------------------------------------------------------
    def save_images(self, images, custom_path, filename_prefix, timestamp,
                    format, quality, ico_sizes, meta_data, blind_watermark,
                    preview, prompt=None, extra_pnginfo=None):
        now = datetime.datetime.now()
        for token, replacement in (("%date", now.strftime("%Y-%m-%d")),
                                   ("%time", now.strftime("%H-%M-%S"))):
            custom_path = custom_path.replace(token, replacement)
            filename_prefix = filename_prefix.replace(token, replacement)

        output_dir = folder_paths.get_output_directory()
        full_output_folder, filename, counter, subfolder, _ = (
            folder_paths.get_save_image_path(
                filename_prefix, output_dir, images[0].shape[1], images[0].shape[0]
            )
        )

        ext = self.EXTENSIONS.get(format, "png")
        save_to_custom = custom_path != ""
        if save_to_custom:
            if not os.path.exists(custom_path):
                try:
                    os.makedirs(custom_path)
                except Exception as e:
                    _log(f"cannot create custom_path {custom_path}", "error")
                    raise FileNotFoundError(f"cannot create custom_path {custom_path}: {e}")
            full_output_folder = os.path.normpath(custom_path)

        # temp dir for the UI previews (only needed when saving elsewhere)
        temp_sub_dir, temp_dir = None, None
        if preview and save_to_custom:
            temp_sub_dir = self._random_name("_savepreview_", "_temp", 16)
            temp_dir = os.path.join(folder_paths.get_temp_directory(), temp_sub_dir)
            os.makedirs(temp_dir, exist_ok=True)

        if meta_data_enabled() and meta_data and format == "ico":
            _log("ico files cannot store metadata, meta_data ignored for this run",
                 "warning")

        results = []
        for image in images:
            i = 255. * image.cpu().numpy()
            img = Image.fromarray(np.clip(i, 0, 255).astype(np.uint8))

            if blind_watermark != "":
                watermarked = self._apply_blind_watermark(img, blind_watermark)
                if watermarked is not None:
                    img = watermarked

            # meta_data is the per-node widget; _build_metadata only knows
            # about the global --disable-metadata flag
            save_kwargs = (self._build_metadata(prompt, extra_pnginfo, format)
                           if meta_data else {})

            # filename with optional timestamp (LayerStyle convention)
            if timestamp == "millisecond":
                file = f'{filename}_{now.strftime("%Y-%m-%d_%H-%M-%S-%f")[:-3]}'
            elif timestamp == "second":
                file = f'{filename}_{now.strftime("%Y-%m-%d_%H-%M-%S")}'
            else:
                file = f"{filename}_{counter:05}"

            # avoid clobbering an existing file
            while os.path.isfile(os.path.join(full_output_folder, f"{file}.{ext}")):
                counter += 1
                if timestamp == "millisecond":
                    file = f'{filename}_{now.strftime("%Y-%m-%d_%H-%M-%S-%f")[:-3]}_{counter:05}'
                elif timestamp == "second":
                    file = f'{filename}_{now.strftime("%Y-%m-%d_%H-%M-%S")}_{counter:05}'
                else:
                    file = f"{filename}_{counter:05}"

            image_file_name = os.path.join(full_output_folder, f"{file}.{ext}")

            # preview for the UI (saved to temp, shown while the real file
            # goes to a custom path)
            preview_filename = ""
            if preview and save_to_custom:
                preview_filename = self._random_name("saveimage_preview_", "_temp", 16) + ".png"
                try:
                    img.save(os.path.join(temp_dir, preview_filename))
                except Exception as e:
                    _log(f"could not write preview to {temp_dir}: {e}", "warning")

            # --- format specific save ---------------------------------
            if format == "png":
                png_kwargs = {"compress_level": (100 - quality) // 10}
                if "pnginfo" in save_kwargs:
                    png_kwargs["pnginfo"] = save_kwargs["pnginfo"]
                img.save(image_file_name, **png_kwargs)
            elif format == "jpg":
                exif = save_kwargs.get("exif")
                jpg_img = self._flatten_alpha(img)  # jpeg has no alpha
                # NOTE: no optimize=True here - the libjpeg-turbo shipped in
                # the Pillow wheels of both ComfyUI installs (verified on
                # ApoPrime py3.12 and HAL py3.13) aborts the encode with
                # "broken data stream" when optimize_coding (Huffman
                # optimisation) is combined with 4:4:4 subsampling and
                # texture-rich content.  subsampling=0 (4:4:4) is kept.
                jpg_img.save(image_file_name, quality=quality, subsampling=0,
                             exif=exif.tobytes() if exif is not None else b"")
            elif format == "webp":
                img.save(image_file_name, quality=quality, method=6, **save_kwargs)
            elif format == "webp (lossless)":
                img.save(image_file_name, lossless=True, quality=100, method=6,
                         **save_kwargs)
            elif format == "tiff":
                img.save(image_file_name, compression="tiff_lzw", **save_kwargs)
            elif format == "ico":
                sizes = [(s, s) for s in self.ICO_PRESETS.get(ico_sizes, (128, 256, 512))]
                # full-resolution source: PIL resamples every entry from it
                img.save(image_file_name, format="ICO", sizes=sizes)
            else:  # pragma: no cover - FORMATS is the closed list
                raise ValueError(f"unsupported format: {format}")

            _log(f"-> Saved image to {image_file_name}")

            if preview:
                if save_to_custom:
                    results.append({
                        "filename": preview_filename,
                        "subfolder": temp_sub_dir,
                        "type": "temp",
                    })
                else:
                    results.append({
                        "filename": f"{file}.{ext}",
                        "subfolder": subfolder,
                        "type": "output",
                    })

            counter += 1

        return {"ui": {"images": results}}


def meta_data_enabled():
    """Core runs with --disable-metadata: honour it like every other
    save node in the ecosystem."""
    if args is None:
        return True
    return not getattr(args, "disable_metadata", False)
